# Example Gammapy spectrum analysis pipeline config file

general:
  datastore: /lfs/l2/hess/users/mimayer/hessfits/latest/pa/Model_Deconvoluted_Prod26/Mpp_Std
  runlist : [23526, 23559, 24542]
  nruns : 5
  outdir : ogip
  create_ogip : true
  run_fit : true

binning:
  equal_log_spacing: true
  emin: 0.1 TeV
  emax: 10 TeV
  nbins: 30

on_region:
  type: circle
  center_x: 83.633083 deg
  center_y: 22.014500 deg
  system: icrs
  radius: 0.3 deg

off_region:
  type: ring
  inner_radius: 0.5 deg
  outer_radius: 0.7 deg

model:
   type: PL
   threshold_low: 0.1 TeV
   threshold_high: 10 TeV
   